name: langchain_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asgiref==3.11.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - backcall==0.2.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - build==1.3.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.23
      - click==8.3.1
      - coloredlogs==15.0.1
      - dataclasses-json==0.6.7
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - distro==1.9.0
      - docopt==0.6.2
      - durationpy==0.10
      - executing==2.2.1
      - fastapi==0.121.3
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - filetype==1.2.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - google-ai-generativelanguage==0.6.6
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-generativeai==0.7.2
      - googleapis-common-protos==1.72.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - grpcio-status==1.62.3
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - importlib-metadata==8.4.0
      - importlib-resources==6.5.2
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - kubernetes==34.1.0
      - langchain==0.2.16
      - langchain-chroma==0.1.4
      - langchain-community==0.2.16
      - langchain-core==0.2.38
      - langchain-google-genai==1.0.10
      - langchain-huggingface==0.0.3
      - langchain-text-splitters==0.2.4
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.9
      - langsmith==0.1.147
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistune==3.1.4
      - mmh3==5.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.5
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - opentelemetry-api==1.27.0
      - opentelemetry-exporter-otlp-proto-common==1.27.0
      - opentelemetry-exporter-otlp-proto-grpc==1.27.0
      - opentelemetry-instrumentation==0.48b0
      - opentelemetry-instrumentation-asgi==0.48b0
      - opentelemetry-instrumentation-fastapi==0.48b0
      - opentelemetry-proto==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - opentelemetry-util-http==0.48b0
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - overrides==7.7.0
      - packaging==24.2
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==12.0.0
      - pipreqs==0.5.0
      - platformdirs==4.5.0
      - posthog==5.4.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==4.25.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pypdf==6.3.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rank-bm25==0.2.2
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.29.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==5.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - stack-data==0.6.3
      - starlette==0.50.0
      - sympy==1.14.0
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.20.3
      - torch==2.9.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==3.5.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - urllib3==2.3.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - wrapt==1.17.3
      - xxhash==3.6.0
      - yarg==0.1.9
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /home/l4t8/anaconda3/envs/langchain_env
